-- MySQL Script generated by MySQL Workbench
-- 10/10/17 10:17:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lol` DEFAULT CHARACTER SET utf8 ;
USE `lol` ;

-- -----------------------------------------------------
-- Table `lol`.`ranks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`ranks` ;

CREATE TABLE IF NOT EXISTS `lol`.`ranks` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `order` INT(2) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unrank` (`name` ASC));


-- -----------------------------------------------------
-- Table `lol`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`positions` ;

CREATE TABLE IF NOT EXISTS `lol`.`positions` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unposition` (`name` ASC));


-- -----------------------------------------------------
-- Table `lol`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`users` ;

CREATE TABLE IF NOT EXISTS `lol`.`users` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `lastname` VARCHAR(50) NULL,
  `arenausername` VARCHAR(50) NOT NULL,
  `summonername` VARCHAR(50) NULL,
  `rankid` INT(5) NULL,
  `positionid` INT(5) NULL,
  `phone` VARCHAR(45) NULL,
  `discount` INT(3) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `creditstatus` INT(1) NULL,
  `SLuserId` INT(11) NULL DEFAULT 0,
  `lolKlub` INT(1) NULL,
  `usertype` INT(2) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `rankid_idx` (`rankid` ASC),
  INDEX `positionid_idx` (`positionid` ASC),
  UNIQUE INDEX `unuser` (`arenausername` ASC, `SLuserId` ASC, `usertype` ASC),
  CONSTRAINT `rankid`
    FOREIGN KEY (`rankid`)
    REFERENCES `lol`.`ranks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `positionid`
    FOREIGN KEY (`positionid`)
    REFERENCES `lol`.`positions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `lol`.`heroes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`heroes` ;

CREATE TABLE IF NOT EXISTS `lol`.`heroes` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unheroe` (`name` ASC));


-- -----------------------------------------------------
-- Table `lol`.`workertype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`workertype` ;

CREATE TABLE IF NOT EXISTS `lol`.`workertype` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uwktype` (`name` ASC));


-- -----------------------------------------------------
-- Table `lol`.`workers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`workers` ;

CREATE TABLE IF NOT EXISTS `lol`.`workers` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(50) NULL,
  `workertypeid` INT(5) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unworker` (`email` ASC),
  INDEX `fkwrktype_idx` (`workertypeid` ASC),
  CONSTRAINT `fkwrktype`
    FOREIGN KEY (`workertypeid`)
    REFERENCES `lol`.`workertype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `lol`.`userheroresult`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`userheroresult` ;

CREATE TABLE IF NOT EXISTS `lol`.`userheroresult` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `userid` INT(9) NOT NULL,
  `heroid` INT(5) NULL,
  `matchdate` DATE NULL,
  `matchtime` TIME NULL,
  `workerid` INT(5) NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `useridfk_idx` (`userid` ASC),
  INDEX `heroidfk_idx` (`heroid` ASC),
  INDEX `wrkidfl_idx` (`workerid` ASC),
  UNIQUE INDEX `usrherodate` (`userid` ASC, `heroid` ASC, `matchtime` ASC, `matchdate` ASC),
  CONSTRAINT `heroidfk`
    FOREIGN KEY (`heroid`)
    REFERENCES `lol`.`heroes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `useridfk`
    FOREIGN KEY (`userid`)
    REFERENCES `lol`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `wrkidfl`
    FOREIGN KEY (`workerid`)
    REFERENCES `lol`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `lol`.`credit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`credit` ;

CREATE TABLE IF NOT EXISTS `lol`.`credit` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `userid` INT(9) NULL,
  `value` INT(4) NULL,
  `workerid` INT(5) NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `expired` INT(2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fkuserid_idx` (`userid` ASC),
  INDEX `fkwrkid_idx` (`workerid` ASC),
  CONSTRAINT `fkuserid`
    FOREIGN KEY (`userid`)
    REFERENCES `lol`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkwrkid`
    FOREIGN KEY (`workerid`)
    REFERENCES `lol`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `lol`.`reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`reservations` ;

CREATE TABLE IF NOT EXISTS `lol`.`reservations` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `timedate` DATETIME NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `computers` VARCHAR(100) NOT NULL,
  `userid` INT(9) NULL,
  `workerid` INT(5) NULL,
  `confirmed` INT(2) NULL,
  `confirmworkerid` INT(5) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniqres` (`timedate` ASC, `computers` ASC, `userid` ASC),
  INDEX `fkresusrid_idx` (`userid` ASC),
  INDEX `fkreswrkid_idx` (`workerid` ASC),
  CONSTRAINT `fkresusrid`
    FOREIGN KEY (`userid`)
    REFERENCES `lol`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkreswrkid`
    FOREIGN KEY (`workerid`)
    REFERENCES `lol`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = '					';


-- -----------------------------------------------------
-- Table `lol`.`informations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`informations` ;

CREATE TABLE IF NOT EXISTS `lol`.`informations` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `tittle` VARCHAR(45) NULL,
  `text` TEXT(1000) NULL,
  `workerid` INT(5) NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `wrkidfl_idx` (`workerid` ASC),
  CONSTRAINT `wrkidflinf`
    FOREIGN KEY (`workerid`)
    REFERENCES `lol`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `lol`.`suppliers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`suppliers` ;

CREATE TABLE IF NOT EXISTS `lol`.`suppliers` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `lol`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`orders` ;

CREATE TABLE IF NOT EXISTS `lol`.`orders` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `workerid` INT(5) NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `supplierid` INT(5) NULL,
  PRIMARY KEY (`id`),
  INDEX `wrkidfl_idx` (`workerid` ASC),
  INDEX `fkruplierid_idx` (`supplierid` ASC),
  CONSTRAINT `wrkidflinf0`
    FOREIGN KEY (`workerid`)
    REFERENCES `lol`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fksuplierid`
    FOREIGN KEY (`supplierid`)
    REFERENCES `lol`.`suppliers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `lol`.`producttype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`producttype` ;

CREATE TABLE IF NOT EXISTS `lol`.`producttype` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `porind` (`id` ASC),
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `lol`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`products` ;

CREATE TABLE IF NOT EXISTS `lol`.`products` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `typeid` INT(5) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `porind` (`id` ASC),
  INDEX `fkprodtype_idx` (`typeid` ASC),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uniqueproduct` (`name` ASC, `typeid` ASC),
  CONSTRAINT `fkprodtype`
    FOREIGN KEY (`typeid`)
    REFERENCES `lol`.`producttype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `lol`.`supplies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`supplies` ;

CREATE TABLE IF NOT EXISTS `lol`.`supplies` (
  `id` INT(5) NOT NULL,
  `status` INT(2) NULL COMMENT 'status: 1 - na stanju; 2-prodato.',
  `amount` INT(5) NULL,
  `orderid` INT(5) NULL,
  `productid` INT(5) NULL,
  `price` FLOAT(10,2) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `suppind` (`id` ASC),
  UNIQUE INDEX `uniqusupplie` (`orderid` ASC, `productid` ASC),
  INDEX `fkprodid_idx` (`productid` ASC),
  CONSTRAINT `fkprodid`
    FOREIGN KEY (`productid`)
    REFERENCES `lol`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkorderid`
    FOREIGN KEY (`orderid`)
    REFERENCES `lol`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `lol`.`BonusHours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`BonusHours` ;

CREATE TABLE IF NOT EXISTS `lol`.`BonusHours` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `numHours` INT(3) NOT NULL,
  `SLuserId` INT(11) NULL,
  `monthNum` INT(3) NULL,
  INDEX `porind` (`id` ASC),
  UNIQUE INDEX `uniqcalculation` (`numHours` ASC, `SLuserId` ASC, `monthNum` ASC));


-- -----------------------------------------------------
-- Table `lol`.`sellingproducts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`sellingproducts` ;

CREATE TABLE IF NOT EXISTS `lol`.`sellingproducts` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `typeid` INT(5) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `selporind` (`id` ASC),
  INDEX `fkselprodtype_idx` (`typeid` ASC),
  UNIQUE INDEX `nametypeselprod` (`name` ASC, `typeid` ASC),
  CONSTRAINT `fkprodtype0`
    FOREIGN KEY (`typeid`)
    REFERENCES `lol`.`producttype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `lol`.`sellingproductsprices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`sellingproductsprices` ;

CREATE TABLE IF NOT EXISTS `lol`.`sellingproductsprices` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `selingproductid` INT(5) NOT NULL,
  `value` FLOAT(6,2) NULL,
  `pricetype` VARCHAR(45) NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `selporind` (`id` ASC),
  INDEX `fkslproductid_idx` (`selingproductid` ASC),
  UNIQUE INDEX `uniqueprice` (`selingproductid` ASC, `value` ASC, `pricetype` ASC),
  CONSTRAINT `fkslproductid`
    FOREIGN KEY (`selingproductid`)
    REFERENCES `lol`.`sellingproducts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `lol`.`bills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`bills` ;

CREATE TABLE IF NOT EXISTS `lol`.`bills` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `workerid` INT(5) NULL,
  `userid` INT(9) NULL,
  `billsum` FLOAT(6,2) NULL,
  `pricetype` VARCHAR(45) NULL,
  `type` INT(3) NULL COMMENT '1 - regular bill\n2 - shift start\n3 - shift end\n4 - shift bill',
  `tstamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `billsindex` (`id` ASC));


-- -----------------------------------------------------
-- Table `lol`.`billsrows`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`billsrows` ;

CREATE TABLE IF NOT EXISTS `lol`.`billsrows` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `billrid` INT(5) NULL,
  `numProducts` INT(2) NULL,
  `sellingproductpriceid` INT(5) NULL,
  `price` FLOAT(6,2) NULL,
  `sellingproductid` INT(5) NULL,
  INDEX `billsindex` (`id` ASC),
  INDEX `billfkid_idx` (`billrid` ASC),
  CONSTRAINT `billfkid`
    FOREIGN KEY (`billrid`)
    REFERENCES `lol`.`bills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `lol`.`transactionallog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`transactionallog` ;

CREATE TABLE IF NOT EXISTS `lol`.`transactionallog` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `monthid` INT(9) NULL,
  `logtype` INT(5) NULL,
  `comment` VARCHAR(100) NULL,
  `tstamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `logindex` (`id` ASC),
  UNIQUE INDEX `loguniq` (`monthid` ASC, `logtype` ASC));


-- -----------------------------------------------------
-- Table `lol`.`sellingproductsdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`sellingproductsdetails` ;

CREATE TABLE IF NOT EXISTS `lol`.`sellingproductsdetails` (
  `id` INT(5) NOT NULL,
  `quantity` INT(2) NULL,
  `productid` INT(5) NULL,
  `selingproductid` INT(5) NULL,
  INDEX `selporind` (`id` ASC),
  INDEX `fkproduct_idx` (`productid` ASC),
  INDEX `fksellprodid_idx` (`selingproductid` ASC),
  CONSTRAINT `fkproduct`
    FOREIGN KEY (`productid`)
    REFERENCES `lol`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fksellprodid`
    FOREIGN KEY (`selingproductid`)
    REFERENCES `lol`.`sellingproducts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `lol`.`shifts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`shifts` ;

CREATE TABLE IF NOT EXISTS `lol`.`shifts` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `starttime` DATETIME NOT NULL,
  `endtime` DATETIME NULL,
  `status` INT(1) NOT NULL,
  `userstart` INT(9) NULL,
  `userend` INT(9) NULL,
  INDEX `uniqueshift` (`id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC));


-- -----------------------------------------------------
-- Table `lol`.`shiftbill`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `lol`.`shiftbill` ;

CREATE TABLE IF NOT EXISTS `lol`.`shiftbill` (
  `id` INT(9) NOT NULL AUTO_INCREMENT,
  `shiftid` INT(5) NULL,
  `billid` INT(5) NULL,
  PRIMARY KEY (`id`),
  INDEX `sbshiftid_idx` (`shiftid` ASC),
  INDEX `sbbillsid_idx` (`billid` ASC),
  UNIQUE INDEX `sbunique` (`shiftid` ASC, `billid` ASC),
  CONSTRAINT `sbshiftid`
    FOREIGN KEY (`shiftid`)
    REFERENCES `lol`.`shifts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `sbbillsid`
    FOREIGN KEY (`billid`)
    REFERENCES `lol`.`bills` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
